#!/usr/bin/python
import sys
sys.path.append('/usr/local/lib/python2.7/')
from xbee import ZigBee
import MySQLdb
import serial

################################################
class myXbeeApi(ZigBee):
#make the database connection
	
	def onData(self,pkg):
		db = MySQLdb.connect(host="localhost", user="kegerator", passwd="k3gs3v3r", db="kegerator")
		#get header for IO data
		if pkg["code"]==0x92:
			#print "Samples %s-> %s" % (pkg["data"]["mac"],pkg["data"]["dsamples"])
			#Eventually this will go to a database or text file or something.
			#print "Samples %s" % (pkg["data"]["dsamples"][0])
			#Convert it to decimal.
			decimalvalue = pkg["data"]["dsamples"][0] * 256 + pkg["data"]["dsamples"][1]
			print "Keg value = %d" % decimalvalue
			#Prep to put into database
			cursor = db.cursor()
			#Get the last value
			cursor.execute("select * from kegs order by created_at desc limit 1")
			result = cursor.fetchall()
			for record in result:
				lastweight = record[1]
			#got the last weight, so comapre and insert into the database if different.
			if abs(lastweight-decimalvalue) > 4:
				print "Inserting into db.  Old: %d" % lastweight
				print "New: %d" % decimalvalue
				print ("INSERT into kegs(kegweight, created_at, updated_at) values(%d, Now(), Now());" % decimalvalue)
				sqlexecute = cursor.execute("INSERT into kegs(kegweight, created_at, updated_at) values(%d, Now(), Now());" % decimalvalue)
				print cursor.rowcount
				cursor.close()
				db.commit()
				db.close()
		elif pkg["code,"]==0x97:
			print "Remote AT %s-> %s [%s]" % (pkg["data"]["mac"],pkg["data"]["cmd"],pkg["data"]["status"])
			
################################################

api=myXbeeApi("/dev/ttyUSB3",9600)

	
